/**
 * Bibliothèque d'éléments pour le constructeur de champs personnalisés.
 * Chaque élément définit son type, sa catégorie, ses dimensions par défaut et minimales.
 */

import type { LibraryElement, LibraryCategory } from '@/types/customField';

/* --- Labels des catégories --- */

export const LIBRARY_CATEGORY_LABELS: Readonly<Record<LibraryCategory, string>> = {
  match: 'Match',
  text: 'Texte',
  data: 'Données',
  players: 'Joueurs',
  media: 'Médias',
  composed: 'Composés',
};

/* --- Labels du constructeur de champs --- */

export const CUSTOM_FIELD_LABELS = {
  /* Section principale */
  sectionCustomFields: 'Layout libre',
  bodyType14Label: 'Layout libre (champs personnalisés)',

  /* Modes */
  fullPageMode: 'Mode pleine page',
  fullPageModeHint: 'Masque le header pour utiliser tout le canvas',
  snapToGrid: 'Aimanter à la grille',
  showGuides: 'Afficher les guides',
  gridSize: 'Taille de la grille',

  /* Bibliothèque */
  libraryTitle: 'Bibliothèque',
  librarySearch: 'Rechercher un élément...',
  libraryEmpty: 'Aucun élément trouvé',
  addField: 'Ajouter au canvas',

  /* Champs */
  fieldProperties: 'Propriétés du champ',
  fieldLabel: 'Nom du champ',
  fieldPosition: 'Position',
  fieldSize: 'Taille',
  fieldX: 'X',
  fieldY: 'Y',
  fieldWidth: 'Largeur',
  fieldHeight: 'Hauteur',
  fieldZIndex: 'Ordre (Z)',
  fieldLocked: 'Verrouillé',
  fieldVisible: 'Visible',
  fieldDelete: 'Supprimer le champ',
  fieldDuplicate: 'Dupliquer le champ',

  /* Style du champ */
  fieldStyleTitle: 'Style du champ',
  fieldBgColor: 'Couleur de fond',
  fieldBorderColor: 'Couleur de bordure',
  fieldBorderWidth: 'Épaisseur de bordure',
  fieldBorderRadius: 'Rayon de bordure',
  fieldPadding: 'Marge interne',
  fieldBgOpacity: 'Opacité du fond',

  /* Couches */
  layersTitle: 'Couches',
  layerMoveUp: 'Monter',
  layerMoveDown: 'Descendre',
  layerToFront: 'Premier plan',
  layerToBack: 'Arrière-plan',

  /* Contraintes */
  canvasFull: 'Canvas complet. Supprimez un champ pour en ajouter un nouveau.',
  fieldOutOfBounds: 'Champ hors limites du canvas',
  maxFieldsReached: 'Nombre maximal de champs atteint',

  /* Validations */
  validateLayout: 'Vérifier le layout',
  validationOk: 'Aucun problème détecté',
  validationOverlap: 'Chevauchement détecté',
  validationOutOfBounds: 'Champ hors limites',

  /* Config éléments */
  configTextContent: 'Contenu',
  configTextFontSize: 'Taille de police',
  configTextFontWeight: 'Épaisseur',
  configTextAlign: 'Alignement',
  configTextTransform: 'Casse',
  configSide: 'Côté',
  configSideLeft: 'Gauche',
  configSideRight: 'Droite',
  configShowFlag: 'Afficher le drapeau',
  configShowLabel: 'Afficher le label',
  configShowPeriod: 'Afficher la période',
  configShowBox: 'Afficher le cadre',
  configShowClock: 'Afficher l\'horloge',
  configStatIndex: 'Ligne de stat',
  configBarIndex: 'Barre',
  configPhotoKey: 'Clé photo',
  configPhotoShape: 'Forme',
  configPhotoCircle: 'Cercle',
  configPhotoSquare: 'Carré',
  configImageSrc: 'Source image',
  configImageFit: 'Ajustement',
  configImageCover: 'Couvrir',
  configImageContain: 'Contenir',
  configImageFill: 'Étirer',
  configShapeType: 'Forme',
  configShapeRectangle: 'Rectangle',
  configShapeCircle: 'Cercle',
  configShapeRounded: 'Rectangle arrondi',
  configShapeFillColor: 'Couleur de remplissage',
  configShapeBorderColor: 'Bordure',
  configSeparatorOrientation: 'Orientation',
  configSeparatorHorizontal: 'Horizontale',
  configSeparatorVertical: 'Verticale',
  configSeparatorThickness: 'Épaisseur',
  configSeparatorColor: 'Couleur',

  /* Presets */
  sectionPresets: 'Presets',
  presetSaveField: 'Sauvegarder le champ',
  presetSaveLayout: 'Sauvegarder l\u2019\u00e9cran',
  presetLoad: 'Charger un preset',
  presetSaveTitle: 'Sauvegarder un preset',
  presetLoadTitle: 'Charger un preset',
  presetNamePlaceholder: 'Nom du preset',
  presetScopeField: 'Champ s\u00e9lectionn\u00e9',
  presetScopeLayout: '\u00c9cran complet',
  presetEmpty: 'Aucun preset sauvegard\u00e9',
  presetSaved: 'Preset sauvegard\u00e9',
  presetLoaded: 'Preset charg\u00e9',
  presetDeleted: 'Preset supprim\u00e9',
  presetExported: 'Preset export\u00e9',
  presetImported: 'Preset import\u00e9',
  presetImportError: 'Erreur lors de l\u2019import du preset',
  presetDeleteConfirm: 'Supprimer ce preset ?',
  presetSave: 'Sauvegarder',
  presetCancel: 'Annuler',
  presetConfirm: 'Confirmer',
  presetDelete: 'Supprimer',
  presetExport: 'Exporter',
  presetImport: 'Importer',
  presetRename: 'Renommer',
  presetNoFieldSelected: 'S\u00e9lectionnez un champ pour le sauvegarder',
  presetNoFields: 'Ajoutez des champs au canvas pour sauvegarder un \u00e9cran',
  presetLoadReplace: 'Remplacer le layout actuel',
  presetLoadMerge: 'Ajouter au layout actuel',
  presetFieldCount: 'champ(s)',
} as const;

/* --- Bibliothèque d'éléments --- */

export const LIBRARY_ELEMENTS: readonly LibraryElement[] = [
  /* --- Match --- */
  {
    type: 'score-display',
    label: 'Score',
    category: 'match',
    defaultWidth: 120,
    defaultHeight: 100,
    minWidth: 60,
    minHeight: 50,
    icon: 'hash',
  },
  {
    type: 'clock-display',
    label: 'Horloge',
    category: 'match',
    defaultWidth: 200,
    defaultHeight: 100,
    minWidth: 100,
    minHeight: 50,
    icon: 'clock',
  },
  {
    type: 'period-display',
    label: 'Période',
    category: 'match',
    defaultWidth: 200,
    defaultHeight: 60,
    minWidth: 80,
    minHeight: 40,
    icon: 'timer',
  },
  {
    type: 'team-name',
    label: 'Nom d\'équipe',
    category: 'match',
    defaultWidth: 200,
    defaultHeight: 80,
    minWidth: 80,
    minHeight: 40,
    icon: 'shield',
  },
  {
    type: 'flag-display',
    label: 'Drapeau',
    category: 'match',
    defaultWidth: 100,
    defaultHeight: 70,
    minWidth: 50,
    minHeight: 40,
    icon: 'flag',
  },
  {
    type: 'timeout-display',
    label: 'Temps morts',
    category: 'match',
    defaultWidth: 200,
    defaultHeight: 60,
    minWidth: 80,
    minHeight: 40,
    icon: 'pause-circle',
  },
  {
    type: 'shootout-display',
    label: 'Tirs au but',
    category: 'match',
    defaultWidth: 300,
    defaultHeight: 60,
    minWidth: 120,
    minHeight: 40,
    icon: 'target',
  },

  /* --- Texte --- */
  {
    type: 'text-block',
    label: 'Bloc de texte',
    category: 'text',
    defaultWidth: 400,
    defaultHeight: 80,
    minWidth: 80,
    minHeight: 40,
    icon: 'type',
  },

  /* --- Données --- */
  {
    type: 'stat-line',
    label: 'Ligne de stat',
    category: 'data',
    defaultWidth: 500,
    defaultHeight: 60,
    minWidth: 200,
    minHeight: 40,
    icon: 'bar-chart-2',
  },
  {
    type: 'bar-compare',
    label: 'Barre comparative',
    category: 'data',
    defaultWidth: 500,
    defaultHeight: 60,
    minWidth: 200,
    minHeight: 40,
    icon: 'git-compare',
  },

  /* --- Joueurs --- */
  {
    type: 'player-photo',
    label: 'Photo joueur',
    category: 'players',
    defaultWidth: 150,
    defaultHeight: 150,
    minWidth: 60,
    minHeight: 60,
    icon: 'user',
  },

  /* --- Médias --- */
  {
    type: 'image-block',
    label: 'Image',
    category: 'media',
    defaultWidth: 300,
    defaultHeight: 200,
    minWidth: 60,
    minHeight: 60,
    icon: 'image',
  },
  {
    type: 'shape-block',
    label: 'Forme',
    category: 'media',
    defaultWidth: 200,
    defaultHeight: 200,
    minWidth: 40,
    minHeight: 40,
    icon: 'square',
  },
  {
    type: 'separator-line',
    label: 'Séparateur',
    category: 'media',
    defaultWidth: 400,
    defaultHeight: 4,
    minWidth: 40,
    minHeight: 4,
    icon: 'minus',
  },

  /* --- Composés (body types existants) --- */
  {
    type: 'header-block',
    label: 'Header complet',
    category: 'composed',
    defaultWidth: 1920,
    defaultHeight: 200,
    minWidth: 400,
    minHeight: 100,
    icon: 'layout-dashboard',
  },
  {
    type: 'penalty-column',
    label: 'Colonne de pénalités',
    category: 'composed',
    defaultWidth: 200,
    defaultHeight: 600,
    minWidth: 100,
    minHeight: 200,
    icon: 'columns',
  },
  {
    type: 'body-type-1',
    label: 'Stats centrées (Type 1)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'align-center',
  },
  {
    type: 'body-type-2',
    label: 'Stats gauche/droite (Type 2)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'columns',
  },
  {
    type: 'body-type-3',
    label: 'Stats joueur (Type 3)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'user',
  },
  {
    type: 'body-type-4',
    label: 'Célébration de but (Type 4)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'trophy',
  },
  {
    type: 'body-type-5',
    label: 'Fiche joueur (Type 5)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'id-card',
  },
  {
    type: 'body-type-6',
    label: 'Classement (Type 6)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'list-ordered',
  },
  {
    type: 'body-type-7',
    label: 'Score final (Type 7)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'flag-triangle-right',
  },
  {
    type: 'body-type-8',
    label: 'Texte libre (Type 8)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'file-text',
  },
  {
    type: 'body-type-9',
    label: 'Face-à-face (Type 9)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'users',
  },
  {
    type: 'body-type-10',
    label: 'Chronologie (Type 10)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'clock',
  },
  {
    type: 'body-type-11',
    label: 'Barres comparatives (Type 11)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'bar-chart',
  },
  {
    type: 'body-type-12',
    label: 'Composition d\'équipe (Type 12)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'users',
  },
  {
    type: 'body-type-13',
    label: 'Calendrier (Type 13)',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'calendar',
  },
];
