/* Tous les textes UI de l'application, centralisés ici. */

export const EDITOR_LABELS = {
  appTitle: 'Scoreboard Editor',

  /* Groupes de sections */
  groupContenu: 'Contenu',
  groupApparence: 'Apparence',
  groupHorloge: 'Horloge',

  /* Sections */
  sectionBodyType: 'Type de corps',
  sectionPenalties: 'Colonnes de pénalités',
  sectionHeader: 'Header',
  sectionClock: 'Horloge',
  sectionFonts: 'Polices',
  sectionTitles: 'Titre(s)',
  sectionStats: 'Lignes de stats',
  sectionPlayerStats: 'Stats joueur',
  sectionPenaltiesPrefix: 'Pénalités',
  sectionColorsBg: 'Couleurs - Background',
  sectionColorsHeader: 'Couleurs - Header',
  sectionColorsBody: 'Couleurs - Corps',
  sectionColorsPenalties: 'Couleurs - Pénalités',
  sectionPresets: 'Presets de couleurs',

  /* Champs */
  team1Label: 'Équipe 1',
  team2Label: 'Équipe 2',
  score1Label: 'Score 1',
  score2Label: 'Score 2',
  showPenalties: 'Afficher les colonnes',
  showClock: "Afficher l'horloge",
  timeLabel: 'Temps',
  activePhase: 'Phase active',
  noPhase: '-- aucune --',
  phaseOptions: 'Options de phases et transitions',
  phaseDuration: 'Durée :',
  phaseTransition: 'À 0:00 :',
  phaseTransitionStop: '-- stop --',
  addPhase: 'Ajouter une phase',
  clockBoxLabel: 'Cadre horloge',
  clockBoxNever: 'Jamais',
  clockBoxAlways: 'Toujours',
  clockBoxStopped: 'Horloge arrêtée',
  clockBoxRunning: 'Horloge en marche',

  /* Polices */
  fontTeams: "Noms d'équipes / Scores",
  fontClock: 'Horloge / Période',
  fontBody: 'Titres / Stats / Pénalités',

  /* Titres */
  titleCenter: 'Titre central',
  titleLeft: 'Titre gauche',
  titleRight: 'Titre droite',

  /* Stats */
  statValLeft: 'Val. G',
  statLabel: 'Label',
  statValRight: 'Val. D',
  addStatLine: 'Ajouter une ligne',

  /* Player stats */
  showPlayerPhoto: 'Afficher photo joueur',
  playerVariable: 'Variable',
  playerNumber: 'No',
  playerName: 'Nom Prénom',
  playerValue: 'Valeur',

  /* Pénalités */
  penaltyTime: 'Temps',
  penaltyNumber: 'No',
  addPenalty: 'Ajouter',

  /* Couleurs */
  bgModeUniform: 'Couleur unie',
  bgModeGradient: 'Dégradé',
  colorBgUniform: 'Couleur de fond',
  colorBgTop: 'Haut',
  colorBgMid: 'Milieu',
  colorBgBot: 'Bas',
  colorTeamName: "Noms d'équipes",
  colorScore: 'Scores',
  colorScoreBox: 'Cadre score',
  colorScoreBoxNone: 'Aucun cadre',
  colorTime: 'Horloge',
  colorClockBox: 'Cadre horloge',
  colorPeriod: 'Période',
  colorTitleText: 'Titres',
  colorStatVal: 'Valeurs stats',
  colorStatLabel: 'Labels stats',
  colorPenaltyTime: 'Temps',
  colorPenaltyNumber: 'Numéros',

  /* Demo / Timer */
  demoTitle: 'TIMER',
  demoStart: 'START',
  demoStop: 'STOP',
  demoReset: 'RESET',
  demoTransitionPrefix: 'À 0:00',
  demoTransitionStop: 'stop',

  /* Goal (type 4) */
  sectionGoal: 'Célébration de but',
  goalScoringTeamSide: 'Côté équipe marqueuse',
  goalSideLeft: 'Gauche',
  goalSideRight: 'Droite',
  goalScorerName: 'Nom du buteur',
  goalScorerNumber: 'Numéro',
  goalTime: 'Temps du but',
  goalPeriod: 'Période',
  goalCountMatch: 'Buts dans le match',
  goalCountTournament: 'Buts dans le tournoi',
  goalAssist1Name: 'Assist 1 - Nom',
  goalAssist1Number: 'Assist 1 - No',
  goalAssist2Name: 'Assist 2 - Nom',
  goalAssist2Number: 'Assist 2 - No',

  /* Player Card (type 5) */
  sectionPlayerCard: 'Fiche joueur',
  playerCardTitle: 'Titre',
  playerCardSubtitle: 'Sous-titre',
  playerCardName: 'Nom du joueur',
  playerCardNumber: 'Numéro',
  playerCardTeam: 'Équipe (NOC)',
  playerCardStatLabel: 'Label',
  playerCardStatValue: 'Valeur',
  playerCardAddStat: 'Ajouter une stat',

  /* Standings (type 6) */
  sectionStandings: 'Classement',
  standingsTitle: 'Titre',
  standingsTeam: 'Équipe',
  standingsHighlight: 'Surligner',
  standingsAddRow: 'Ajouter une équipe',

  /* Final Score (type 7) */
  sectionFinalScore: 'Score final',
  finalScoreTitle: 'Titre',
  finalScoreShowGwg: 'Afficher le but gagnant',
  finalScoreGwgPlayer: 'Joueur GWG',
  finalScoreGwgTeam: 'Équipe GWG',
  finalScoreGwgTime: 'Temps GWG',
  finalScoreOvertimeNote: 'Note prolongation',
  finalScorePeriodLabel: 'Période',
  finalScoreLeft: 'G',
  finalScoreRight: 'D',
  finalScoreAddPeriod: 'Ajouter une période',

  /* Free Text (type 8) */
  sectionFreeText: 'Texte libre',
  freeTextContent: 'Texte',
  freeTextFontSize: 'Taille',
  freeTextAlign: 'Alignement',
  freeTextBold: 'Gras',
  freeTextAddLine: 'Ajouter une ligne',
  freeTextAlignLeft: 'Gauche',
  freeTextAlignCenter: 'Centre',
  freeTextAlignRight: 'Droite',

  /* Head to Head (type 9) */
  sectionHeadToHead: 'Face-à-face',
  headToHeadTitle: 'Titre',
  headToHeadPlayerName: 'Nom',
  headToHeadPlayerNumber: 'Numéro',
  headToHeadPlayerTeam: 'Équipe',
  headToHeadStatLabel: 'Stat',
  headToHeadStatLeft: 'Val. G',
  headToHeadStatRight: 'Val. D',
  headToHeadAddStat: 'Ajouter une stat',

  /* Timeline (type 10) */
  sectionTimeline: 'Chronologie',
  timelineTitle: 'Titre',
  timelineEventPeriod: 'Pér.',
  timelineEventTime: 'Temps',
  timelineEventType: 'Type',
  timelineEventDescription: 'Description',
  timelineEventTeam: 'Équipe',
  timelineAddEvent: 'Ajouter un événement',
  timelineTypeGoal: 'But',
  timelineTypePenalty: 'Pénalité',
  timelineTypeTimeout: 'Temps mort',
  timelineTypePeriod: 'Période',

  /* Bar Chart (type 11) */
  sectionBarChart: 'Barres comparatives',
  barChartTitle: 'Titre',
  barChartLabel: 'Label',
  barChartValueLeft: 'Val. G',
  barChartValueRight: 'Val. D',
  barChartFormat: 'Format',
  barChartFormatPercent: 'Pourcentage',
  barChartFormatAbsolute: 'Absolu',
  barChartAddRow: 'Ajouter une barre',

  /* Roster (type 12) */
  sectionRoster: "Composition d'équipe",
  rosterTitle: 'Titre',
  rosterTeam: 'Équipe',
  rosterCoach: 'Entraîneur',
  rosterPlayerNumber: 'No',
  rosterPlayerName: 'Nom',
  rosterPlayerPosition: 'Pos.',
  rosterAddPlayer: 'Ajouter un joueur',

  /* Schedule (type 13) */
  sectionSchedule: 'Calendrier',
  scheduleTitle: 'Titre',
  scheduleDate: 'Date',
  scheduleTime: 'Heure',
  scheduleTeamLeft: 'Éq. G',
  scheduleTeamRight: 'Éq. D',
  scheduleScoreLeft: 'Sc. G',
  scheduleScoreRight: 'Sc. D',
  scheduleStatus: 'Statut',
  scheduleVenue: 'Lieu',
  scheduleAddMatch: 'Ajouter un match',
  scheduleStatusUpcoming: 'À venir',
  scheduleStatusLive: 'En cours',
  scheduleStatusFinished: 'Terminé',

  /* Header - Timeouts */
  sectionTimeouts: 'Temps morts',
  showTimeoutsLabel: 'Afficher les temps morts',
  timeoutsLeftLabel: 'Temps morts G',
  timeoutsRightLabel: 'Temps morts D',

  /* Header - Shootout */
  sectionShootout: 'Tirs au but',
  showShootoutLabel: 'Afficher les tirs au but',
  shootoutScored: 'B',
  shootoutMissed: 'R',
  shootoutPending: '-',
  shootoutAddAttempt: 'Ajouter un tir',

  /* Médias */
  mediaUploadPhoto: 'Photo',
  mediaUploadBackground: 'Arrière-plan',
  mediaSelectFile: 'Choisir un fichier',
  mediaDragDrop: 'ou glisser-déposer ici',
  mediaRemove: 'Supprimer',
  mediaFormatError: 'Format non supporté. Utilisez PNG, JPEG ou WebP.',
  mediaVideoFormatError: 'Format non supporté. Utilisez MP4 ou WebM.',
  scorerPhoto: 'Photo du buteur',
  playerPhoto: 'Photo du joueur',

  /* Galerie de photos joueurs */
  sectionPhotos: 'Photos des joueurs',
  photoTeam: 'Équipe',
  photoNumber: 'Numéro',
  photoPlayerName: 'Nom du joueur',
  photoAdd: 'Ajouter une photo',
  photoEmpty: 'Aucune photo enregistrée',
  photoDeleteConfirm: 'Supprimer cette photo ?',
  photoAdded: 'Photo ajoutée',
  photoDeleted: 'Photo supprimée',
  photoReplace: 'Remplacer',

  /* Logos */
  sectionLogos: 'Logos',
  logoTeamTab: 'Équipes',
  logoCompetitionTab: 'Compétition',
  logoSponsorTab: 'Sponsor',
  logoTeamCode: 'Code équipe',
  logoName: 'Nom',
  logoAdd: 'Ajouter un logo',
  logoEmpty: 'Aucun logo enregistré',
  logoDeleteConfirm: 'Supprimer ce logo ?',
  logoAdded: 'Logo ajouté',
  logoDeleted: 'Logo supprimé',
  logoMode: 'Affichage équipes',
  logoModeFlag: 'Drapeau',
  logoModeLogo: 'Logo',
  logoModeBoth: 'Les deux',
  logoShowCompetition: 'Afficher le logo compétition',
  logoShowSponsor: 'Afficher le logo sponsor',
  logoPosition: 'Position',
  logoSize: 'Taille',
  logoPositionTopLeft: 'Haut gauche',
  logoPositionTopRight: 'Haut droite',
  logoPositionTopCenter: 'Haut centre',
  logoPositionBottomLeft: 'Bas gauche',
  logoPositionBottomRight: 'Bas droite',
  logoPositionBottomCenter: 'Bas centre',

  /* Fond d'écran */
  sectionBackground: 'Arrière-plan média',
  bgMediaNone: 'Aucun',
  bgMediaImage: 'Image',
  bgMediaVideo: 'Vidéo',
  bgMediaSelectImage: 'Choisir une image de fond',
  bgMediaSelectVideo: 'Choisir une vidéo de fond',

  /* Barre d'outils */
  openOutput: 'Ouvrir la sortie',
  screenshot: 'Capture',
  print: 'Imprimer',
  screenshotSuccess: 'Capture téléchargée',
  clipboardSuccess: 'Copié dans le presse-papier',

  /* Dimensions du template */
  sectionTemplateSize: 'Dimensions du template',
  templateWidth: 'Largeur',
  templateHeight: 'Hauteur',
  templatePreset: 'Preset',
  templateCustom: 'Personnalisé',

  /* Tailles de police */
  sectionFontSizes: 'Tailles de police',
  fontSizeTeamName: "Noms d'équipes",
  fontSizeScore: 'Scores',
  fontSizeClockTime: 'Horloge',
  fontSizePeriod: 'Période',
  fontSizeTitle: 'Titres',
  fontSizeStatValue: 'Valeurs stats',
  fontSizeStatLabel: 'Labels stats',
  fontSizePenaltyTime: 'Temps pénalité',
  fontSizePenaltyNumber: 'Numéro pénalité',
  fontSizeAuto: 'Auto',

  /* Templates */
  templates: 'Templates',
  templateSave: 'Sauvegarder',
  templateSaveAs: 'Sauvegarder sous...',
  templateLoad: 'Charger',
  templateDelete: 'Supprimer',
  templateDuplicate: 'Dupliquer',
  templateRename: 'Renommer',
  templateExport: 'Exporter',
  templateImport: 'Importer',
  templateNew: 'Nouveau',
  templateNamePlaceholder: 'Nom du template',
  templateSaveTitle: 'Sauvegarder le template',
  templateRenameTitle: 'Renommer le template',
  templateDeleteConfirm: 'Confirmer la suppression',
  templateDeleteMessage: 'Voulez-vous vraiment supprimer ce template ?',
  templateEmptyList: 'Aucun template sauvegardé',
  templateImportError: 'Erreur lors de l\u2019import du fichier',
  templateSaved: 'Template sauvegardé',
  templateLoaded: 'Template chargé',
  templateDeleted: 'Template supprimé',
  templateDuplicated: 'Template dupliqué',
  templateRenamed: 'Template renommé',
  templateExported: 'Template exporté',
  templateImported: 'Template importé',
  templateCancel: 'Annuler',
  templateConfirm: 'Confirmer',
  templatePresets: 'Templates prédéfinis',
  templateUpdated: 'Template mis à jour',

  /* Frame Data API */
  frameRecordStart: 'Enregistrer',
  frameRecordStop: 'Arrêter',
  frameRecordReset: 'Réinitialiser',
  frameExportSnapshot: 'Exporter snapshot',
  frameExportMatch: 'Exporter match',
  frameExportStream: 'Exporter stream',
  frameCount: 'Frames',
  frameRecording: 'Enregistrement en cours',

  /* Mode opérateur */
  operatorTitle: 'Mode opérateur',
  operatorScore: 'Score',
  operatorClock: 'Horloge',
  operatorPenalties: 'Pénalités',
  operatorPhase: 'Phase',
  operatorStart: 'START',
  operatorStop: 'STOP',
  operatorReset: 'RESET',
  operatorNextPhase: 'Phase suivante',
  operatorAddPenalty: 'Pénalité',
  operatorPenaltyNumber: 'No joueur',
  operatorPenaltyDuration: 'Durée',
  operatorFullscreen: 'Plein écran',
  operatorBackToEditor: 'Retour éditeur',
  operatorWaiting: 'En attente de données...',
  operatorKeyboardHelp: 'Raccourcis : Espace = Start/Stop, R = Reset, P = Phase suivante',
} as const;
