/**
 * D\u00e9finitions des \u00e9l\u00e9ments de la biblioth\u00e8que pour le constructeur de champs.
 * Chaque \u00e9l\u00e9ment d\u00e9finit son type, sa cat\u00e9gorie, ses dimensions par d\u00e9faut et minimales.
 */

import type { LibraryElement } from '@/types/customField';

export const LIBRARY_ELEMENTS: readonly LibraryElement[] = [
  /* --- Match --- */
  {
    type: 'score-display',
    label: 'Score',
    description: 'Affiche le score d\u2019une \u00e9quipe (configurable gauche/droite)',
    category: 'match',
    defaultWidth: 180,
    defaultHeight: 120,
    minWidth: 60,
    minHeight: 50,
    icon: 'hash',
  },
  {
    type: 'clock-display',
    label: 'Horloge',
    description: 'Horloge de match avec d\u00e9compte en temps r\u00e9el',
    category: 'match',
    defaultWidth: 340,
    defaultHeight: 120,
    minWidth: 100,
    minHeight: 50,
    icon: 'clock',
  },
  {
    type: 'period-display',
    label: 'P\u00e9riode',
    description: 'Nom de la p\u00e9riode en cours (ex. 1st PERIOD)',
    category: 'match',
    defaultWidth: 250,
    defaultHeight: 60,
    minWidth: 80,
    minHeight: 40,
    icon: 'timer',
  },
  {
    type: 'team-name',
    label: 'Nom d\'\u00e9quipe',
    description: 'Nom ou code de l\u2019\u00e9quipe s\u00e9lectionn\u00e9e',
    category: 'match',
    defaultWidth: 600,
    defaultHeight: 160,
    minWidth: 80,
    minHeight: 40,
    icon: 'shield',
  },
  {
    type: 'flag-display',
    label: 'Drapeau',
    description: 'Drapeau du pays de l\u2019\u00e9quipe',
    category: 'match',
    defaultWidth: 120,
    defaultHeight: 80,
    minWidth: 50,
    minHeight: 40,
    icon: 'flag',
  },
  {
    type: 'timeout-display',
    label: 'Temps morts',
    description: 'Indicateur des temps morts restants',
    category: 'match',
    defaultWidth: 280,
    defaultHeight: 60,
    minWidth: 80,
    minHeight: 40,
    icon: 'pause-circle',
  },
  {
    type: 'shootout-display',
    label: 'Tirs au but',
    description: 'Affichage des tirs au but',
    category: 'match',
    defaultWidth: 400,
    defaultHeight: 60,
    minWidth: 120,
    minHeight: 40,
    icon: 'target',
  },

  /* --- Texte --- */
  {
    type: 'text-block',
    label: 'Bloc de texte',
    description: 'Texte libre personnalisable (titre, label, etc.)',
    category: 'text',
    defaultWidth: 400,
    defaultHeight: 80,
    minWidth: 80,
    minHeight: 40,
    icon: 'type',
  },

  /* --- Donn\u00e9es --- */
  {
    type: 'stat-line',
    label: 'Ligne de stat',
    description: 'Ligne de statistique comparative (gauche vs droite)',
    category: 'data',
    defaultWidth: 500,
    defaultHeight: 60,
    minWidth: 200,
    minHeight: 40,
    icon: 'bar-chart-2',
  },
  {
    type: 'bar-compare',
    label: 'Barre comparative',
    description: 'Barre de comparaison graphique entre deux valeurs',
    category: 'data',
    defaultWidth: 500,
    defaultHeight: 80,
    minWidth: 200,
    minHeight: 40,
    icon: 'git-compare',
  },

  /* --- Joueurs --- */
  {
    type: 'player-photo',
    label: 'Photo joueur',
    description: 'Photo d\u2019un joueur (cercle ou carr\u00e9)',
    category: 'players',
    defaultWidth: 150,
    defaultHeight: 150,
    minWidth: 60,
    minHeight: 60,
    icon: 'user',
  },
  {
    type: 'player-row',
    label: 'Joueur',
    description: 'Ligne joueur : num\u00e9ro, nom et position',
    category: 'players',
    defaultWidth: 400,
    defaultHeight: 50,
    minWidth: 150,
    minHeight: 40,
    icon: 'user-round',
  },
  {
    type: 'player-list',
    label: 'Liste de joueurs',
    description: 'Groupe de joueurs avec titre (ligne, gardiens, etc.)',
    category: 'players',
    defaultWidth: 450,
    defaultHeight: 250,
    minWidth: 200,
    minHeight: 100,
    icon: 'users',
  },

  /* --- But --- */
  {
    type: 'goal-scorer',
    label: 'Buteur',
    description: 'Nom, num\u00e9ro et photo du buteur',
    category: 'goal',
    defaultWidth: 400,
    defaultHeight: 120,
    minWidth: 200,
    minHeight: 60,
    icon: 'circle-dot',
  },
  {
    type: 'goal-assists',
    label: 'Assistants',
    description: 'Noms et num\u00e9ros des assistants (1 ou 2)',
    category: 'goal',
    defaultWidth: 400,
    defaultHeight: 80,
    minWidth: 200,
    minHeight: 50,
    icon: 'handshake',
  },
  {
    type: 'goal-details',
    label: 'D\u00e9tails du but',
    description: 'Temps, p\u00e9riode et compteur de buts',
    category: 'goal',
    defaultWidth: 300,
    defaultHeight: 80,
    minWidth: 150,
    minHeight: 50,
    icon: 'clock',
  },

  /* --- \u00c9quipe / Staff --- */
  {
    type: 'staff-row',
    label: 'Membre du staff',
    description: 'R\u00f4le et nom d\u2019un membre du staff',
    category: 'team',
    defaultWidth: 350,
    defaultHeight: 50,
    minWidth: 150,
    minHeight: 40,
    icon: 'briefcase',
  },
  {
    type: 'staff-list',
    label: 'Liste du staff',
    description: 'Groupe de membres du staff avec titre',
    category: 'team',
    defaultWidth: 400,
    defaultHeight: 200,
    minWidth: 200,
    minHeight: 100,
    icon: 'users-round',
  },

  /* --- Tableau --- */
  {
    type: 'data-table',
    label: 'Tableau de donn\u00e9es',
    description: 'Tableau configurable (colonnes et lignes libres)',
    category: 'table',
    defaultWidth: 600,
    defaultHeight: 300,
    minWidth: 300,
    minHeight: 120,
    icon: 'table',
  },

  /* --- \u00c9v\u00e9nement / Chronologie --- */
  {
    type: 'timeline-event',
    label: '\u00c9v\u00e9nement',
    description: 'Un \u00e9v\u00e9nement du match (but, p\u00e9nalit\u00e9, temps mort)',
    category: 'event',
    defaultWidth: 500,
    defaultHeight: 50,
    minWidth: 250,
    minHeight: 40,
    icon: 'activity',
  },
  {
    type: 'timeline-list',
    label: 'Chronologie',
    description: 'Liste chronologique des \u00e9v\u00e9nements du match',
    category: 'event',
    defaultWidth: 600,
    defaultHeight: 300,
    minWidth: 300,
    minHeight: 120,
    icon: 'list',
  },

  /* --- Calendrier --- */
  {
    type: 'schedule-match',
    label: 'Match',
    description: 'Un match (date, heure, \u00e9quipes, score, statut)',
    category: 'schedule',
    defaultWidth: 550,
    defaultHeight: 50,
    minWidth: 300,
    minHeight: 40,
    icon: 'calendar-days',
  },
  {
    type: 'schedule-list',
    label: 'Programme',
    description: 'Liste de matchs \u00e0 venir ou termin\u00e9s',
    category: 'schedule',
    defaultWidth: 650,
    defaultHeight: 300,
    minWidth: 350,
    minHeight: 120,
    icon: 'calendar-range',
  },

  /* --- Fiche joueur (joueurs) --- */
  {
    type: 'player-card',
    label: 'Fiche joueur',
    description: 'Fiche compl\u00e8te : photo, nom, \u00e9quipe et statistiques',
    category: 'players',
    defaultWidth: 500,
    defaultHeight: 450,
    minWidth: 250,
    minHeight: 200,
    icon: 'id-card',
  },

  /* --- Score par p\u00e9riode (match) --- */
  {
    type: 'period-score-row',
    label: 'Score par p\u00e9riode',
    description: 'D\u00e9tail des scores par p\u00e9riode (P1, P2, P3, OT\u2026)',
    category: 'match',
    defaultWidth: 500,
    defaultHeight: 60,
    minWidth: 250,
    minHeight: 40,
    icon: 'columns',
  },

  /* --- M\u00e9dias --- */
  {
    type: 'image-block',
    label: 'Image',
    description: 'Image ou logo depuis un fichier',
    category: 'media',
    defaultWidth: 300,
    defaultHeight: 200,
    minWidth: 60,
    minHeight: 60,
    icon: 'image',
  },
  {
    type: 'shape-block',
    label: 'Forme',
    description: 'Forme g\u00e9om\u00e9trique (rectangle, cercle, arrondi)',
    category: 'media',
    defaultWidth: 200,
    defaultHeight: 200,
    minWidth: 40,
    minHeight: 40,
    icon: 'square',
  },
  {
    type: 'separator-line',
    label: 'S\u00e9parateur',
    description: 'Ligne de s\u00e9paration horizontale ou verticale',
    category: 'media',
    defaultWidth: 400,
    defaultHeight: 4,
    minWidth: 40,
    minHeight: 4,
    icon: 'minus',
  },

  /* --- Compos\u00e9s (body types existants) --- */
  {
    type: 'header-block',
    label: 'Header complet',
    description: 'En-t\u00eate complet avec drapeaux, scores et horloge',
    category: 'composed',
    defaultWidth: 1920,
    defaultHeight: 200,
    minWidth: 400,
    minHeight: 100,
    icon: 'layout-dashboard',
  },
  {
    type: 'penalty-column',
    label: 'Colonne de p\u00e9nalit\u00e9s',
    description: 'Colonne des p\u00e9nalit\u00e9s en cours',
    category: 'composed',
    defaultWidth: 200,
    defaultHeight: 600,
    minWidth: 100,
    minHeight: 200,
    icon: 'columns',
  },
  {
    type: 'body-type-14',
    label: 'Stats centr\u00e9es (Type 14)',
    description: 'Statistiques centr\u00e9es avec titre',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'align-center',
  },
  {
    type: 'body-type-2',
    label: 'Stats gauche/droite (Type 2)',
    description: 'Statistiques avec deux titres lat\u00e9raux',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'columns',
  },
  {
    type: 'body-type-3',
    label: 'Stats joueur (Type 3)',
    description: 'Fiche de statistiques d\u2019un joueur',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'user',
  },
  {
    type: 'body-type-4',
    label: 'C\u00e9l\u00e9bration de but (Type 4)',
    description: 'Bandeau de c\u00e9l\u00e9bration de but',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'trophy',
  },
  {
    type: 'body-type-5',
    label: 'Fiche joueur (Type 5)',
    description: 'Fiche d\u2019identit\u00e9 compl\u00e8te d\u2019un joueur',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'id-card',
  },
  {
    type: 'body-type-6',
    label: 'Classement (Type 6)',
    description: 'Tableau de classement',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'list-ordered',
  },
  {
    type: 'body-type-7',
    label: 'Score final (Type 7)',
    description: 'Affichage du score final',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'flag-triangle-right',
  },
  {
    type: 'body-type-8',
    label: 'Texte libre (Type 8)',
    description: 'Zone de texte libre multi-lignes',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'file-text',
  },
  {
    type: 'body-type-9',
    label: 'Face-\u00e0-face (Type 9)',
    description: 'Confrontation face-\u00e0-face de deux \u00e9quipes',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'users',
  },
  {
    type: 'body-type-10',
    label: 'Chronologie (Type 10)',
    description: 'Chronologie des \u00e9v\u00e9nements du match',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'clock',
  },
  {
    type: 'body-type-11',
    label: 'Barres comparatives (Type 11)',
    description: 'Ensemble de barres comparatives',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'bar-chart',
  },
  {
    type: 'body-type-12',
    label: 'Composition d\'\u00e9quipe (Type 12)',
    description: 'Composition d\u2019\u00e9quipe avec les joueurs',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'users',
  },
  {
    type: 'body-type-13',
    label: 'Calendrier (Type 13)',
    description: 'Calendrier des matchs \u00e0 venir',
    category: 'composed',
    defaultWidth: 1200,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 200,
    icon: 'calendar',
  },
];
