import type { HockeyNation } from '@/types/nations';

export const HOCKEY_NATIONS: readonly HockeyNation[] = [
  { noc: 'CAN', iso: 'ca', name: 'Canada' },
  { noc: 'USA', iso: 'us', name: 'États-Unis' },
  { noc: 'RUS', iso: 'ru', name: 'Russie' },
  { noc: 'SWE', iso: 'se', name: 'Suède' },
  { noc: 'FIN', iso: 'fi', name: 'Finlande' },
  { noc: 'CZE', iso: 'cz', name: 'Tchéquie' },
  { noc: 'SVK', iso: 'sk', name: 'Slovaquie' },
  { noc: 'SUI', iso: 'ch', name: 'Suisse' },
  { noc: 'GER', iso: 'de', name: 'Allemagne' },
  { noc: 'DEN', iso: 'dk', name: 'Danemark' },
  { noc: 'NOR', iso: 'no', name: 'Norvège' },
  { noc: 'LAT', iso: 'lv', name: 'Lettonie' },
  { noc: 'AUT', iso: 'at', name: 'Autriche' },
  { noc: 'FRA', iso: 'fr', name: 'France' },
  { noc: 'BLR', iso: 'by', name: 'Biélorussie' },
  { noc: 'KAZ', iso: 'kz', name: 'Kazakhstan' },
  { noc: 'SLO', iso: 'si', name: 'Slovénie' },
  { noc: 'HUN', iso: 'hu', name: 'Hongrie' },
  { noc: 'GBR', iso: 'gb', name: 'Grande-Bretagne' },
  { noc: 'POL', iso: 'pl', name: 'Pologne' },
  { noc: 'ITA', iso: 'it', name: 'Italie' },
  { noc: 'JPN', iso: 'jp', name: 'Japon' },
  { noc: 'KOR', iso: 'kr', name: 'Corée du Sud' },
  { noc: 'CHN', iso: 'cn', name: 'Chine' },
  { noc: 'ROU', iso: 'ro', name: 'Roumanie' },
  { noc: 'CRO', iso: 'hr', name: 'Croatie' },
  { noc: 'UKR', iso: 'ua', name: 'Ukraine' },
  { noc: 'EST', iso: 'ee', name: 'Estonie' },
  { noc: 'LTU', iso: 'lt', name: 'Lituanie' },
  { noc: 'SRB', iso: 'rs', name: 'Serbie' },
  { noc: 'BUL', iso: 'bg', name: 'Bulgarie' },
];
